### ISSUE TITLE
Do not require md5sum for artifacts

### ISSUE THREAD

**Issue by vbusch** [jboss-dockerfiles/dogen#105]
The EnMasse community images need to be built using the 'latest' artifacts.  To import these using sources, we need the latest md5sum.  The md5sum might change after every build.  Can we have an option to skip the md5sum, or have it pull & recalculate it?

**Comment by goldmann** [comment]
Yep, this makes sense. We should squeeze it in 2.0.0.

**Comment by goldmann** [comment]
Proposed quick fix available as PR #107.
