### ISSUE TITLE
virtual packages now fail due to #100

### ISSUE THREAD

**Issue by jmtd** [jboss-dockerfiles/dogen#109]
The change in #100 unfortunately does not work with virtual packages, like java.

`yum install java` will actually install something like `java-1.8.0-openjdk-devel-1.8.0.121-0.b13.el7_3.x86_64`, so `rpm -qi java` will fail.

**Comment by jmtd** [comment]
This might be user error here, java is probably not actually a real package name. I suspect yum's package name resolver is just more generous than rpm's: the real package name is probably `java-1.8.0-openjdk`.

**Comment by goldmann** [comment]
Same thing applies to `mysql` which can be provided by the `mariadb` package.

**Comment by goldmann** [comment]
In general - the solution (or rather workaround) is to specify the correct package name. I would probably leave the code as-is and monitor it. For now I would close this issue.

**Comment by l-d-j** [comment]
basically this issue is related to any rpm which provides alternative way of installing (also with some yum plugins you can even do yum install /usr/bin/java). I think we should close is as wont fix and require users to provide proper package names.

**Comment by jmtd** [comment]
Agreed, thank guys
