### ISSUE TITLE
Remove information and configuration sections in envs

### ISSUE THREAD

**Issue by goldmann** [jboss-dockerfiles/dogen#127]
Instead we should have a single `envs` section that contains an array of environment variables. The old "information" envs should have a new key added: `information` (or similar) with boolean value.

This makes it easier to understand the image.yaml.

**Comment by dbecvarik** [comment]
+1
IIRC this is only for generation documentation, so dogen can just provide env section and ignore attributes it doesn't care about?

**Comment by goldmann** [comment]
Exactly. This is my idea.
