### ISSUE TITLE
Dogen fails if md5 is not set for 'local' artifacts

### ISSUE THREAD

**Issue by lulf** [jboss-dockerfiles/dogen#145]
Using dogen 2.0. In my image.yaml, if I have the following:

````
sources:
    - artifact: myfile.tar.gz
````

I run dogen mounting `pwd` into /tmp/output inside the dogen container, and put the myfile.tar.gz inside the build/ folder. Dogen is invoked with /tmp/output/build as the destination folder.

I would expect that the local file myfile.tar.gz is added to the resulting image. However, dogen throws an error of not being able to find the artifact. In addition, the helpful hint on where to download it, i.e. "Please download the 'myfile.tar.gz' artifact manually and save it as '/tmp/output/build/myfile.tar.gz' is missing unless I also add the 'hint' field. 

If I do this:

```
sources:
    - artifact: myfile.tar.gz
      md5: <md5sum of myfile.tar.gz>
```

Then dogen is successful creating the Dockerfile. 

I would like to be able to omit the md5 field and still be able to generate the Dockerfile, as this is useful for generating Dockerfiles for locally built artifacts.

A detailed example can be found here: https://pastebin.com/31fqRGUa

**Comment by goldmann** [comment]
Fix proposed in #149.

**Comment by goldmann** [comment]
@lulf Can you try to upgrade to 2.0.1? https://github.com/jboss-dockerfiles/dogen/releases/tag/2.0.1

**Comment by lulf** [comment]
@goldmann It works well, thanks!
