### ISSUE TITLE
sources not cleaned up if there aren't any scripts

### ISSUE THREAD

**Issue by jmtd** [jboss-dockerfiles/dogen#25]
/tmp/scripts gets cleaned up only if there are scripts.

sources are out in /tmp/scripts/sources

if there are no scripts, this does not get cleaned up.

Prior to cct there would always be scripts because there was no other way of running things in the image, but now we could be doing it with cct.

Related: Ideally, I think we should put the sources in /tmp/sources rather than under /tmp/scripts, but we would need to transition a bunch of stuff to the new location (or add a compat symlink in the short term)

**Comment by goldmann** [comment]
Closing because #24 fixed this.
