### ISSUE TITLE
openshift in default template

### ISSUE THREAD

**Issue by jmtd** [jboss-dockerfiles/dogen#37]
We have the following in our default template

```
{%- if openshift %}
# Switch to the user 185 for OpenShift usage
USER 185
{% else %}
USER jboss
{% endif %}
```

If we merge #36 , then the YAML files relying on this can set `user:` instead of `openshift:`, which is a bit more generic, and we could just get rid of the above section.

**Comment by l-d-j** [comment]
fixed by #36
