### ISSUE TITLE
auto-detecting repo files in the output dir is a bit unusual

### ISSUE THREAD

**Issue by jmtd** [jboss-dockerfiles/dogen#39]
I was a bit surprised that we look at the _output_ directory for .repo files to enable the additional_repos feature, rather than a directory adjacent to the input image.yaml. I usually expect the output directory to only contain things generated by the tool, so it is safe to delete, or could be missing entirely.

**Comment by jmtd** [comment]
I've since realised that the way we use this is to put files into the image via `additional-scripts`, which means they're in the output directory because dogen copied them there. This still feels a bit weird to me.

**Comment by goldmann** [comment]
Right, this is a hacky feature, maybe we can come up with something better? Maybe we can populate `sources` with anything we have in the `additional-scripts`?

**Comment by goldmann** [comment]
I think this issues is no longer valid since we moved everything to the repo plugin where I do not see this behavior now. Generally speaking `additional-scripts` should and will be removed.

**Comment by goldmann** [comment]
Created: #133.
