### ISSUE TITLE
Don't add version when FROM image is scratch

### ISSUE THREAD

**Issue by rcernich** [jboss-dockerfiles/dogen#55]
Currently, the generated Dockerfile ends up with something like, FROM scratch:1.0.

**Comment by rcernich** [comment]
Not sure how much can be done with this.  There are many other issues using dogen when using FROM scratch, e.g., can't execute install scripts.

**Comment by goldmann** [comment]
Yah, this tool is designed to be used with one of the RHEL/CentOS/Fedora base images and not as a replacement for creating base images, for which `scratch` was invented.
