### ISSUE TITLE
DOGEN_CCT_SOURCES_PREFIX versus DOGEN_SOURCES_CACHE

### ISSUE THREAD

**Issue by jmtd** [jboss-dockerfiles/dogen#65]
these are two ways to do the same thing, it seems, one CCT specific, one not.

DOGEN_CCT_SOURCES_PREFIX must be specified with a trailing slash -- the code just pre-pends this value to the artifact name it wants so the slash must exist.

DOGEN_SOURCES_CACHE adds the slash, so you shouldn't include it (but it will probably work if you do)

**Comment by goldmann** [comment]
Dogen does support only `DOGEN_SOURCES_CACHE`. Closing it. We should think how to solve it in CCT.
