### ISSUE TITLE
review class attributes for generator

### ISSUE THREAD

**Issue by l-d-j** [jboss-dockerfiles/dogen#7]
Creating class attribute self.cfg in configure method like this 
https://github.com/jboss-dockerfiles/dogen/blob/master/dogen/generator.py#L97
is not a good idea. Its hard to find where is created/initialized.
Also this class have a lot of attributes. Maybe it will be solved by plugin architecture in future.

**Comment by goldmann** [comment]
Closing as the plugin architecture was implemented.
