### ISSUE TITLE
use repos plugin to supply additional repos w/o disabling existing ones

### ISSUE THREAD

**Issue by jmtd** [jboss-dockerfiles/dogen#98]
Currently if we supply any .repo files and enable the repos.py plugin, then the yum invocations will disable any other repo files. So a user must supply all repos. It would be nice if we could supply additional repos (like say epel) but not have to supply the OS repos too.

**Comment by goldmann** [comment]
I think this should be done by custom template. We cannot and we should not cover all cases.

**Comment by goldmann** [comment]
I'm closing this. We can revisit it again if there will be a valid use case.
